// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akqlzigielcrdavsmuzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrcWx6aWdpZWxjcmRhdnNtdXp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTAwNzEsImV4cCI6MjA2NjA4NjA3MX0.XTfVnrcqMH0whx_73gniKAi5c8NvFgIFbpvqYF8eGss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);